### ISSUE TITLE
微信无法正常启动问题

### ISSUE THREAD

**Issue by twinfishxixi** [zq1997/deepin-wine#164]
大神好！
微信上周还能正常工作，这周进行了系统升级后就发生异常，点击微信图标后无反应，任务管理器发现`WeChat.exe`进程出现几秒就自行消失。
在排查过程中试过了执行全部四个层级，即全部卸载再重新安装，故障依旧。
目前安装了微信、QQ、钉钉、阿里旺旺、同花顺几个软件，发现只有微信是调用`deepin-wine6-stable`下的`wine`来启动`WeChat.exe`，试了通过在终端里使用`deepin-wine5`和`deepin-wine5-stable`下的`wine`，`WeChat.exe`都可以启动，但存在输入框无输入显示、打开分享链接内置浏览器无显示问题，不知道是不是`wine`版本问题。此外，也试过对`/opt/apps/com.qq.weixin.deepin/files`中的`run.sh`进行修改，即
```
39  export APPRUN_CMD="$HOME/.deepinwine/deepin-wine6-stable/bin/wine"
```
将`deepin-wine6-stable`改为`deepin-wine5`或`deepin-wine5-stable`，状况依旧。

附上终端执行结果和计算机信息，还望大神帮忙排查，万分感谢！

在终端执行`run.sh`的情况如下：
```
twinfish@Twinfish-PC:/opt/apps/com.qq.weixin.deepin/files$ ./run.sh 
Run Deepin-WeChat 3.2.1.154deepin8 c:/Program Files/Tencent/WeChat/WeChat.exe
run Deepin-WeChat progress pid 
总用量 0
lrwxrwxrwx 1 twinfish twinfish 10 5月  13 17:22 c: -> ../drive_c
lrwxrwxrwx 1 twinfish twinfish 10 5月  13 17:19 com1 -> /dev/ttyS0
lrwxrwxrwx 1 twinfish twinfish 10 5月  13 17:19 com10 -> /dev/ttyS9
lrwxrwxrwx 1 twinfish twinfish 11 5月  13 17:19 com11 -> /dev/ttyS10
lrwxrwxrwx 1 twinfish twinfish 11 5月  13 17:19 com12 -> /dev/ttyS11
lrwxrwxrwx 1 twinfish twinfish 11 5月  13 17:19 com13 -> /dev/ttyS12
lrwxrwxrwx 1 twinfish twinfish 11 5月  13 17:19 com14 -> /dev/ttyS13
lrwxrwxrwx 1 twinfish twinfish 11 5月  13 17:19 com15 -> /dev/ttyS14
lrwxrwxrwx 1 twinfish twinfish 11 5月  13 17:19 com16 -> /dev/ttyS15
lrwxrwxrwx 1 twinfish twinfish 11 5月  13 17:19 com17 -> /dev/ttyS16
lrwxrwxrwx 1 twinfish twinfish 11 5月  13 17:19 com18 -> /dev/ttyS17
lrwxrwxrwx 1 twinfish twinfish 11 5月  13 17:19 com19 -> /dev/ttyS18
lrwxrwxrwx 1 twinfish twinfish 10 5月  13 17:19 com2 -> /dev/ttyS1
lrwxrwxrwx 1 twinfish twinfish 11 5月  13 17:19 com20 -> /dev/ttyS19
lrwxrwxrwx 1 twinfish twinfish 11 5月  13 17:19 com21 -> /dev/ttyS20
lrwxrwxrwx 1 twinfish twinfish 11 5月  13 17:19 com22 -> /dev/ttyS21
lrwxrwxrwx 1 twinfish twinfish 11 5月  13 17:19 com23 -> /dev/ttyS22
lrwxrwxrwx 1 twinfish twinfish 11 5月  13 17:19 com24 -> /dev/ttyS23
lrwxrwxrwx 1 twinfish twinfish 11 5月  13 17:19 com25 -> /dev/ttyS24
lrwxrwxrwx 1 twinfish twinfish 11 5月  13 17:19 com26 -> /dev/ttyS25
lrwxrwxrwx 1 twinfish twinfish 11 5月  13 17:19 com27 -> /dev/ttyS26
lrwxrwxrwx 1 twinfish twinfish 11 5月  13 17:19 com28 -> /dev/ttyS27
lrwxrwxrwx 1 twinfish twinfish 11 5月  13 17:19 com29 -> /dev/ttyS28
lrwxrwxrwx 1 twinfish twinfish 10 5月  13 17:19 com3 -> /dev/ttyS2
lrwxrwxrwx 1 twinfish twinfish 11 5月  13 17:19 com30 -> /dev/ttyS29
lrwxrwxrwx 1 twinfish twinfish 11 5月  13 17:19 com31 -> /dev/ttyS30
lrwxrwxrwx 1 twinfish twinfish 11 5月  13 17:19 com32 -> /dev/ttyS31
lrwxrwxrwx 1 twinfish twinfish 10 5月  13 17:19 com4 -> /dev/ttyS3
lrwxrwxrwx 1 twinfish twinfish 10 5月  13 17:19 com5 -> /dev/ttyS4
lrwxrwxrwx 1 twinfish twinfish 10 5月  13 17:19 com6 -> /dev/ttyS5
lrwxrwxrwx 1 twinfish twinfish 10 5月  13 17:19 com7 -> /dev/ttyS6
lrwxrwxrwx 1 twinfish twinfish 10 5月  13 17:19 com8 -> /dev/ttyS7
lrwxrwxrwx 1 twinfish twinfish 10 5月  13 17:19 com9 -> /dev/ttyS8
lrwxrwxrwx 1 twinfish twinfish  8 5月  13 16:34 d:: -> /dev/sr0
lrwxrwxrwx 1 twinfish twinfish 14 5月  13 17:22 y: -> /home/twinfish
lrwxrwxrwx 1 twinfish twinfish  1 5月  13 17:22 z: -> /
CallApp Deepin-WeChat c:/Program Files/Tencent/WeChat/WeChat.exe
Disable auto update
rm: 无法删除 '/home/twinfish/.deepinwine/Deepin-WeChat/drive_c/users/twinfish/Application Data/Tencent/WeChat/All Users/config/configEx.ini': 没有那个文件或目录
2021年 05月 13日 星期四 17:22:25 CST:kill WeChat.exe block
cat: /proc/983/maps: 权限不够
cat: /proc/983/maps: 权限不够
cat: /proc/411310/maps: 权限不够
cat: /proc/411310/maps: 权限不够
cat: /proc/411337/maps: 权限不够
cat: /proc/411337/maps: 权限不够
cat: /proc/447488/maps: 没有那个文件或目录
cat: /proc/447488/maps: 没有那个文件或目录
2021年 05月 13日 星期四 17:22:25 CST:tag bottle: 
Traceback (most recent call last):
  File "/home/twinfish/.deepinwine/deepin-wine-helper/get_tray_window", line 28, in <module>
    get_tray_window()
  File "/home/twinfish/.deepinwine/deepin-wine-helper/get_tray_window", line 18, in get_tray_window
    traymanager = bus.get_object("com.deepin.dde.TrayManager", "/com/deepin/dde/TrayManager")
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 243, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 280, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 653, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name com.deepin.dde.TrayManager was not provided by any .service files
2021年 05月 13日 星期四 17:22:25 CST:active bottles: 
/home/twinfish/.deepinwine/Deepin-WeChat/drive_c/Program Files/Tencent/WeChat
twinfish@Twinfish-PC:/opt/apps/com.qq.weixin.deepin/files$ 01b8:fixme:font:get_name_record_codepage encoding 29 not handled, platform 1.
01b8:fixme:font:get_name_record_codepage encoding 29 not handled, platform 1.
01b8:fixme:font:get_name_record_codepage encoding 29 not handled, platform 1.
01b8:fixme:font:get_name_record_codepage encoding 29 not handled, platform 1.
01c0:fixme:font:get_name_record_codepage encoding 29 not handled, platform 1.
01c0:fixme:font:get_name_record_codepage encoding 29 not handled, platform 1.
01c0:fixme:font:get_name_record_codepage encoding 29 not handled, platform 1.
01c0:fixme:font:get_name_record_codepage encoding 29 not handled, platform 1.
01b8:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
01b8:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
01c0:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
01c0:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
01b8:fixme:process:SetProcessDEPPolicy (3): stub
01c4:fixme:ver:GetCurrentPackageId (0553FF00 00000000): stub
01c4:fixme:sync:SetWaitableTimerEx (000000E0, 0553FDB0, 0, 00000000, 00000000, 00000000, 1500) semi-stub
01f4:fixme:iphlpapi:NotifyAddrChange (Handle 0x6c5ff0c, overlapped 0x6c5fef4): stub
01b8:fixme:win:RegisterTouchWindow (000100BE 00000000): stub
01fc:fixme:ole:CoInitializeSecurity 00000000, -1, 00000000, 00000000, 0, 3, 00000000, 0, 00000000 stub
01fc:fixme:wbemprox:client_security_SetBlanket 78191CA4, 06CCAAA8, 10, 0, (null), 3, 3, 00000000, 0x00000000
01fc:fixme:wbemprox:client_security_Release 78191CA4
01fc:fixme:ole:CoInitializeSecurity 00000000, -1, 00000000, 00000000, 0, 3, 00000000, 0, 00000000 stub
01fc:fixme:wbemprox:client_security_SetBlanket 78191CA4, 06CCAAD8, 10, 0, (null), 3, 3, 00000000, 0x00000000
01fc:fixme:wbemprox:client_security_Release 78191CA4
01fc:fixme:ole:CoInitializeSecurity 00000000, -1, 00000000, 00000000, 0, 3, 00000000, 0, 00000000 stub
01fc:fixme:wbemprox:client_security_SetBlanket 78191CA4, 06CCAA08, 10, 0, (null), 3, 3, 00000000, 0x00000000
01fc:fixme:wbemprox:client_security_Release 78191CA4
01f8:fixme:wlanapi:WlanEnumInterfaces (00000001, 00000000, 0600EC5C) semi-stub
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
01fc:fixme:ole:CoInitializeSecurity 00000000, -1, 00000000, 00000000, 0, 3, 00000000, 0, 00000000 stub
01fc:fixme:wbemprox:client_security_SetBlanket 78191CA4, 06CDEC40, 10, 0, (null), 3, 3, 00000000, 0x00000000
01fc:fixme:wbemprox:client_security_Release 78191CA4
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
01fc:fixme:ole:CoInitializeSecurity 00000000, -1, 00000000, 00000000, 0, 3, 00000000, 0, 00000000 stub
01fc:fixme:wbemprox:client_security_SetBlanket 78191CA4, 06CDF5A8, 10, 0, (null), 3, 3, 00000000, 0x00000000
01fc:fixme:wbemprox:client_security_Release 78191CA4
01e0:fixme:winsock:fix_send_is_blocking_state is_blocking = 0, is_EAGAIN = 11
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
01fc:fixme:ole:CoInitializeSecurity 00000000, -1, 00000000, 00000000, 0, 3, 00000000, 0, 00000000 stub
01fc:fixme:wbemprox:client_security_SetBlanket 78191CA4, 06CDF5A8, 10, 0, (null), 3, 3, 00000000, 0x00000000
01fc:fixme:wbemprox:client_security_Release 78191CA4
01fc:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
01fc:fixme:ole:CoInitializeSecurity 00000000, -1, 00000000, 00000000, 0, 3, 00000000, 0, 00000000 stub
01fc:fixme:wbemprox:client_security_SetBlanket 78191CA4, 06CDF530, 10, 0, (null), 3, 3, 00000000, 0x00000000
01fc:fixme:wbemprox:client_security_Release 78191CA4
01fc:err:d3d:wined3d_adapter_init Failed to initialise output, hr 0x80070057.
01e0:fixme:winsock:fix_send_is_blocking_state is_blocking = 0, is_EAGAIN = 11
01e0:fixme:winsock:fix_send_is_blocking_state is_blocking = 0, is_EAGAIN = 11
01e0:fixme:winsock:fix_send_is_blocking_state is_blocking = 0, is_EAGAIN = 11
01b8:fixme:heap:RtlSetHeapInformation 00000000 1 00000000 0 stub
01b8:fixme:ntdll:EtwEventRegister ({d2d578d9-2936-45b6-a09f-30e32715f42d}, 10135670, 1382ED80, 138A9108) stub.
[0513/172227:INFO:exception_record.cc(518)] [QB]Process ID: 436 Type: 1
0210:fixme:nls:RtlGetThreadPreferredUILanguages 00000038, 084AFB90, 00000000 084AFB94
0210:fixme:nls:get_dummy_preferred_ui_language (0x38 084AFB90 00000000 084AFB94) returning a dummy value (current locale)
0210:fixme:nls:RtlGetThreadPreferredUILanguages 00000038, 084AFB90, 06ED21F8 084AFB94
0210:fixme:nls:get_dummy_preferred_ui_language (0x38 084AFB90 06ED21F8 084AFB94) returning a dummy value (current locale)
0210:fixme:winsock:WSALookupServiceBeginW (0x84af818 0x00000ff0 0x84af858) Stub!
[0513/172227:ERROR:network_change_notifier_win.cc(156)] WSALookupServiceBegin failed with: 8
0210:fixme:iphlpapi:NotifyAddrChange (Handle 0x84af994, overlapped 0x6ed31fc): stub
0230:fixme:font:get_name_record_codepage encoding 29 not handled, platform 1.
0230:fixme:font:get_name_record_codepage encoding 29 not handled, platform 1.
0230:fixme:font:get_name_record_codepage encoding 29 not handled, platform 1.
0230:fixme:font:get_name_record_codepage encoding 29 not handled, platform 1.
0230:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0230:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0230:fixme:heap:RtlSetHeapInformation 00000000 1 00000000 0 stub
0234:fixme:resource:GetGuiResources (00000308,0): stub
023c:fixme:winsock:fix_send_is_blocking_state is_blocking = 1, is_EAGAIN = 11

```

计算机信息如下：
```
twinfish@Twinfish-PC:/opt/apps/com.qq.weixin.deepin/files$ inxi -SGxxxr
System:    Host: Twinfish-PC Kernel: 5.4.0-73-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Xfce 4.14.2 
           tk: Gtk 3.24.13 info: xfce4-panel, cairo-dock wm: xfwm4 dm: GDM3 3.36.3, LightDM 1.30.0 
           Distro: Ubuntu 20.04.2 LTS (Focal Fossa) 
Graphics:  Device-1: Intel UHD Graphics 630 vendor: Lenovo driver: i915 v: kernel bus ID: 00:02.0 
           chip ID: 8086:3e98 
           Device-2: NVIDIA GP107GL [Quadro P400] driver: nvidia v: 460.73.01 bus ID: 01:00.0 chip ID: 10de:1cb3 
           Display: x11 server: X.Org 1.20.9 driver: modesetting,nvidia unloaded: fbdev,vesa alternate: nouveau 
           resolution: 1680x1050~60Hz 
           OpenGL: renderer: Quadro P400/PCIe/SSE2 v: 4.6.0 NVIDIA 460.73.01 direct render: Yes 
Repos:     Active apt repos in: /etc/apt/sources.list 
           1: deb http://mirrors.ustc.edu.cn/ubuntu/ focal main restricted
           2: deb http://mirrors.ustc.edu.cn/ubuntu/ focal-updates main restricted
           3: deb http://mirrors.ustc.edu.cn/ubuntu/ focal universe
           4: deb http://mirrors.ustc.edu.cn/ubuntu/ focal-updates universe
           5: deb http://mirrors.ustc.edu.cn/ubuntu/ focal multiverse
           6: deb http://mirrors.ustc.edu.cn/ubuntu/ focal-updates multiverse
           7: deb http://mirrors.ustc.edu.cn/ubuntu/ focal-backports main restricted universe multiverse
           8: deb http://archive.canonical.com/ubuntu focal partner
           9: deb http://mirrors.ustc.edu.cn/ubuntu/ focal-security main restricted
           10: deb http://mirrors.ustc.edu.cn/ubuntu/ focal-security universe
           11: deb http://mirrors.ustc.edu.cn/ubuntu/ focal-security multiverse
           No active apt repos in: /etc/apt/sources.list.d/cairo-dock-team-ubuntu-ppa-bionic.list 
           Active apt repos in: /etc/apt/sources.list.d/cdemu-ubuntu-ppa-bionic.list 
           1: deb http://ppa.launchpad.net/cdemu/ppa/ubuntu focal main
           No active apt repos in: /etc/apt/sources.list.d/cuda-ubuntu1804-11-0-local.list 
           Active apt repos in: /etc/apt/sources.list.d/cybermax-dexter-ubuntu-sdl2-backport-bionic.list 
           1: deb http://ppa.launchpad.net/cybermax-dexter/sdl2-backport/ubuntu focal main
           Active apt repos in: /etc/apt/sources.list.d/deepin-wine.i-m.dev.list 
           1: deb [trusted=yes] https://deepin-wine.i-m.dev /
           No active apt repos in: /etc/apt/sources.list.d/djcj-ubuntu-hybrid-bionic.list 
           No active apt repos in: /etc/apt/sources.list.d/fcitx-team-ubuntu-nightly-bionic.list 
           Active apt repos in: /etc/apt/sources.list.d/font-manager-ubuntu-staging-bionic.list 
           1: deb http://ppa.launchpad.net/font-manager/staging/ubuntu focal main
           Active apt repos in: /etc/apt/sources.list.d/gerardpuig-ubuntu-ppa-bionic.list 
           1: deb http://ppa.launchpad.net/gerardpuig/ppa/ubuntu focal main
           No active apt repos in: /etc/apt/sources.list.d/google-earth-pro.list 
           No active apt repos in: /etc/apt/sources.list.d/hzwhuang-ubuntu-ss-qt5-bionic.list 
           Active apt repos in: /etc/apt/sources.list.d/maarten-baert-ubuntu-simplescreenrecorder-bionic.list 
           1: deb http://ppa.launchpad.net/maarten-baert/simplescreenrecorder/ubuntu focal main
           Active apt repos in: /etc/apt/sources.list.d/mscore-ubuntu-ubuntu-mscore-stable-bionic.list 
           1: deb http://ppa.launchpad.net/mscore-ubuntu/mscore-stable/ubuntu focal main
           Active apt repos in: /etc/apt/sources.list.d/musicbrainz-developers-ubuntu-stable-bionic.list 
           1: deb http://ppa.launchpad.net/musicbrainz-developers/stable/ubuntu focal main
           Active apt repos in: /etc/apt/sources.list.d/oibaf-ubuntu-graphics-drivers-bionic.list 
           1: deb http://ppa.launchpad.net/oibaf/graphics-drivers/ubuntu focal main
           Active apt repos in: /etc/apt/sources.list.d/peek-developers-ubuntu-stable-bionic.list 
           1: deb http://ppa.launchpad.net/peek-developers/stable/ubuntu focal main
           Active apt repos in: /etc/apt/sources.list.d/qbittorrent-team-ubuntu-qbittorrent-stable-bionic.list 
           1: deb http://ppa.launchpad.net/qbittorrent-team/qbittorrent-stable/ubuntu focal main
           Active apt repos in: /etc/apt/sources.list.d/sandromani-ubuntu-gimagereader-bionic.list 
           1: deb http://ppa.launchpad.net/sandromani/gimagereader/ubuntu focal main
           No active apt repos in: /etc/apt/sources.list.d/team-xbmc-ubuntu-kodi-old-bionic.list 
           Active apt repos in: /etc/apt/sources.list.d/team-xbmc-ubuntu-ppa-bionic.list 
           1: deb http://ppa.launchpad.net/team-xbmc/ppa/ubuntu focal main
           Active apt repos in: /etc/apt/sources.list.d/ubuntu-toolchain-r-ubuntu-test-bionic.list 
           1: deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu focal main
           Active apt repos in: /etc/apt/sources.list.d/vscode.list 
           1: deb [arch=amd64,arm64,armhf] http://packages.microsoft.com/repos/code stable main
           No active apt repos in: /etc/apt/sources.list.d/webupd8team-ubuntu-indicator-kdeconnect-bionic.list 
```

**Comment by zq1997** [comment]
不清楚是不是xface不兼容，gnome是能用的

**Comment by twinfishxixi** [comment]
因为从问题发生前后的情况来看，是在做了一次升级后出现目前这个情况的，之前没有做任何配置，直接`apt`安装就搞定。
从`run.sh`执行情况来看，有无啥奇怪的地方呢？特别是其中报错那一段：
```
2021年 05月 13日 星期四 17:22:25 CST:tag bottle: 
Traceback (most recent call last):
  File "/home/twinfish/.deepinwine/deepin-wine-helper/get_tray_window", line 28, in <module>
    get_tray_window()
  File "/home/twinfish/.deepinwine/deepin-wine-helper/get_tray_window", line 18, in get_tray_window
    traymanager = bus.get_object("com.deepin.dde.TrayManager", "/com/deepin/dde/TrayManager")
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 243, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 280, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 653, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name com.deepin.dde.TrayManager was not provided by any .service files
2021年 05月 13日 星期四 17:22:25 CST:active bottles: 
/home/twinfish/.deepinwine/Deepin-WeChat/drive_c/Program Files/Tencent/WeChat
```

**Comment by zq1997** [comment]
报错正常情况也有

**Comment by lghItem** [comment]
权限不够 尝试输入 sudo ./run.sh
