### ISSUE TITLE
Linux Mint Xfce无法启动

### ISSUE THREAD

**Issue by Baloneo** [zq1997/deepin-wine#190]
```
➜  ~ /opt/apps/com.qq.weixin.deepin/files/run.sh     
Run Deepin-WeChat 3.2.1.154deepin8 c:/Program Files/Tencent/WeChat/WeChat.exe
run Deepin-WeChat progress pid 
total 0
lrwxrwxrwx 1 baloneo baloneo 10 8月   5 09:00 c: -> ../drive_c
lrwxrwxrwx 1 baloneo baloneo 10 8月   5 08:58 com1 -> /dev/ttyS0
lrwxrwxrwx 1 baloneo baloneo 10 8月   5 08:58 com10 -> /dev/ttyS9
lrwxrwxrwx 1 baloneo baloneo 11 8月   5 08:58 com11 -> /dev/ttyS10
lrwxrwxrwx 1 baloneo baloneo 11 8月   5 08:58 com12 -> /dev/ttyS11
lrwxrwxrwx 1 baloneo baloneo 11 8月   5 08:58 com13 -> /dev/ttyS12
lrwxrwxrwx 1 baloneo baloneo 11 8月   5 08:58 com14 -> /dev/ttyS13
lrwxrwxrwx 1 baloneo baloneo 11 8月   5 08:58 com15 -> /dev/ttyS14
lrwxrwxrwx 1 baloneo baloneo 11 8月   5 08:58 com16 -> /dev/ttyS15
lrwxrwxrwx 1 baloneo baloneo 11 8月   5 08:58 com17 -> /dev/ttyS16
lrwxrwxrwx 1 baloneo baloneo 11 8月   5 08:58 com18 -> /dev/ttyS17
lrwxrwxrwx 1 baloneo baloneo 11 8月   5 08:58 com19 -> /dev/ttyS18
lrwxrwxrwx 1 baloneo baloneo 10 8月   5 08:58 com2 -> /dev/ttyS1
lrwxrwxrwx 1 baloneo baloneo 11 8月   5 08:58 com20 -> /dev/ttyS19
lrwxrwxrwx 1 baloneo baloneo 11 8月   5 08:58 com21 -> /dev/ttyS20
lrwxrwxrwx 1 baloneo baloneo 11 8月   5 08:58 com22 -> /dev/ttyS21
lrwxrwxrwx 1 baloneo baloneo 11 8月   5 08:58 com23 -> /dev/ttyS22
lrwxrwxrwx 1 baloneo baloneo 11 8月   5 08:58 com24 -> /dev/ttyS23
lrwxrwxrwx 1 baloneo baloneo 11 8月   5 08:58 com25 -> /dev/ttyS24
lrwxrwxrwx 1 baloneo baloneo 11 8月   5 08:58 com26 -> /dev/ttyS25
lrwxrwxrwx 1 baloneo baloneo 11 8月   5 08:58 com27 -> /dev/ttyS26
lrwxrwxrwx 1 baloneo baloneo 11 8月   5 08:58 com28 -> /dev/ttyS27
lrwxrwxrwx 1 baloneo baloneo 11 8月   5 08:58 com29 -> /dev/ttyS28
lrwxrwxrwx 1 baloneo baloneo 10 8月   5 08:58 com3 -> /dev/ttyS2
lrwxrwxrwx 1 baloneo baloneo 11 8月   5 08:58 com30 -> /dev/ttyS29
lrwxrwxrwx 1 baloneo baloneo 11 8月   5 08:58 com31 -> /dev/ttyS30
lrwxrwxrwx 1 baloneo baloneo 11 8月   5 08:58 com32 -> /dev/ttyS31
lrwxrwxrwx 1 baloneo baloneo 10 8月   5 08:58 com4 -> /dev/ttyS3
lrwxrwxrwx 1 baloneo baloneo 10 8月   5 08:58 com5 -> /dev/ttyS4
lrwxrwxrwx 1 baloneo baloneo 10 8月   5 08:58 com6 -> /dev/ttyS5
lrwxrwxrwx 1 baloneo baloneo 10 8月   5 08:58 com7 -> /dev/ttyS6
lrwxrwxrwx 1 baloneo baloneo 10 8月   5 08:58 com8 -> /dev/ttyS7
lrwxrwxrwx 1 baloneo baloneo 10 8月   5 08:58 com9 -> /dev/ttyS8
lrwxrwxrwx 1 baloneo baloneo  8 8月   5 08:56 d:: -> /dev/sr0
lrwxrwxrwx 1 baloneo baloneo  8 8月   5 08:58 lpt1 -> /dev/lp0
lrwxrwxrwx 1 baloneo baloneo 13 8月   5 09:00 y: -> /home/baloneo
lrwxrwxrwx 1 baloneo baloneo  1 8月   5 09:00 z: -> /
CallApp Deepin-WeChat c:/Program Files/Tencent/WeChat/WeChat.exe
Disable auto update
rm: cannot remove '/home/baloneo/.deepinwine/Deepin-WeChat/drive_c/users/baloneo/Application Data/Tencent/WeChat/All Users/config/configEx.ini': No such file or directory
2021年 08月 05日 星期四 09:00:38 CST:kill WeChat.exe block
cat: /proc/831/maps: Permission denied
cat: /proc/831/maps: Permission denied
cat: /proc/936/maps: Permission denied
cat: /proc/936/maps: Permission denied
cat: /proc/6505/maps: No such file or directory
cat: /proc/6505/maps: No such file or directory
2021年 08月 05日 星期四 09:00:38 CST:tag bottle: 
Traceback (most recent call last):
  File "/home/baloneo/.deepinwine/deepin-wine-helper/get_tray_window", line 28, in <module>
    get_tray_window()
  File "/home/baloneo/.deepinwine/deepin-wine-helper/get_tray_window", line 18, in get_tray_window
    traymanager = bus.get_object("com.deepin.dde.TrayManager", "/com/deepin/dde/TrayManager")
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 243, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 280, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 653, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name com.deepin.dde.TrayManager was not provided by any .service files
2021年 08月 05日 星期四 09:00:38 CST:active bottles: 
/home/baloneo/.deepinwine/Deepin-WeChat/drive_c/Program Files/Tencent/WeChat
➜  ~ 0110:fixme:font:get_name_record_codepage encoding 29 not handled, platform 1.
0110:fixme:font:get_name_record_codepage encoding 29 not handled, platform 1.
0110:fixme:font:get_name_record_codepage encoding 29 not handled, platform 1.
0110:fixme:font:get_name_record_codepage encoding 29 not handled, platform 1.
0118:fixme:font:get_name_record_codepage encoding 29 not handled, platform 1.
0118:fixme:font:get_name_record_codepage encoding 29 not handled, platform 1.
0118:fixme:font:get_name_record_codepage encoding 29 not handled, platform 1.
0118:fixme:font:get_name_record_codepage encoding 29 not handled, platform 1.
0110:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0110:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0118:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0118:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0110:fixme:process:SetProcessDEPPolicy (3): stub
0110:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
011c:fixme:ver:GetCurrentPackageId (053FFF00 00000000): stub
011c:fixme:sync:SetWaitableTimerEx (000000E4, 053FFDB0, 0, 00000000, 00000000, 00000000, 1500) semi-stub
0134:fixme:winsock:fix_send_is_blocking_state is_blocking = 0, is_EAGAIN = 11
014c:fixme:iphlpapi:NotifyAddrChange (Handle 0x6f3ff0c, overlapped 0x6f3fef4): stub
0110:fixme:win:RegisterTouchWindow (00010056 00000000): stub
0154:fixme:ole:CoInitializeSecurity 00000000, -1, 00000000, 00000000, 0, 3, 00000000, 0, 00000000 stub
0154:fixme:wbemprox:client_security_SetBlanket 78296CA4, 069C83E0, 10, 0, (null), 3, 3, 00000000, 0x00000000
0154:fixme:wbemprox:client_security_Release 78296CA4
0154:fixme:ole:CoInitializeSecurity 00000000, -1, 00000000, 00000000, 0, 3, 00000000, 0, 00000000 stub
0154:fixme:wbemprox:client_security_SetBlanket 78296CA4, 069C6B60, 10, 0, (null), 3, 3, 00000000, 0x00000000
0154:fixme:wbemprox:client_security_Release 78296CA4
0150:fixme:wlanapi:WlanEnumInterfaces (00000001, 00000000, 05DBEC5C) semi-stub
0154:fixme:ole:CoInitializeSecurity 00000000, -1, 00000000, 00000000, 0, 3, 00000000, 0, 00000000 stub
0154:fixme:wbemprox:client_security_SetBlanket 78296CA4, 052CEFC8, 10, 0, (null), 3, 3, 00000000, 0x00000000
0154:fixme:wbemprox:client_security_Release 78296CA4
0134:fixme:winsock:fix_send_is_blocking_state is_blocking = 0, is_EAGAIN = 11
0134:fixme:winsock:fix_send_is_blocking_state is_blocking = 0, is_EAGAIN = 11
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
0154:fixme:ole:CoInitializeSecurity 00000000, -1, 00000000, 00000000, 0, 3, 00000000, 0, 00000000 stub
0154:fixme:wbemprox:client_security_SetBlanket 78296CA4, 06961CE8, 10, 0, (null), 3, 3, 00000000, 0x00000000
0154:fixme:wbemprox:client_security_Release 78296CA4
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
0154:fixme:ole:CoInitializeSecurity 00000000, -1, 00000000, 00000000, 0, 3, 00000000, 0, 00000000 stub
0154:fixme:wbemprox:client_security_SetBlanket 78296CA4, 052F8D08, 10, 0, (null), 3, 3, 00000000, 0x00000000
0154:fixme:wbemprox:client_security_Release 78296CA4
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
0154:fixme:ole:CoInitializeSecurity 00000000, -1, 00000000, 00000000, 0, 3, 00000000, 0, 00000000 stub
0154:fixme:wbemprox:client_security_SetBlanket 78296CA4, 06961CE8, 10, 0, (null), 3, 3, 00000000, 0x00000000
0154:fixme:wbemprox:client_security_Release 78296CA4
0154:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0154:fixme:ole:CoInitializeSecurity 00000000, -1, 00000000, 00000000, 0, 3, 00000000, 0, 00000000 stub
0154:fixme:wbemprox:client_security_SetBlanket 78296CA4, 069C7008, 10, 0, (null), 3, 3, 00000000, 0x00000000
0154:fixme:wbemprox:client_security_Release 78296CA4
0134:fixme:winsock:fix_send_is_blocking_state is_blocking = 0, is_EAGAIN = 11
0110:fixme:heap:RtlSetHeapInformation 00000000 1 00000000 0 stub
0110:fixme:ntdll:EtwEventRegister ({d2d578d9-2936-45b6-a09f-30e32715f42d}, 10135670, 1382ED80, 138A9108) stub.
[0805/090040:INFO:exception_record.cc(518)] [QB]Process ID: 268 Type: 1
X Error of failed request:  GLXBadFBConfig
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  0 ()
  Serial number of failed request:  313
  Current serial number in output stream:  313

➜  ~ 

```

**Comment by YKY-0110** [comment]
可以看这个 https://blog.csdn.net/u010750137/article/details/104871680
改成 MESA_GL_VERSION_OVERRIDE=4.5 /opt/apps/com.qq.weixin.deepin/files/run.sh
![Screenshot_20210805_094700](https://user-images.githubusercontent.com/51268227/128278457-b9ce185e-9248-4a75-840b-12854c1a6270.jpg)

**Comment by Baloneo** [comment]
已经解决，修改启动文件的命令为
```
/home/foo/start_wechat.sh
```

start_wechat.sh
```
#!/usr/bin/bash
MESA_GL_VERSION_OVERRIDE=4.5 /opt/apps/com.qq.weixin.deepin/files/run.sh
```
