### ISSUE TITLE
微信突然无法使用了！

### ISSUE THREAD

**Issue by rangerzhou** [zq1997/deepin-wine#209]
系统：Linux Mint 20.1 Cinnamon
现象：点击图标后没有登录界面弹出

桌面提示：The Wine configuration in Y:\.deepinwine\Deepin-WeChat is being updated, please wait

QQ可以正常登录

![2021-09-06_12-32](https://user-images.githubusercontent.com/29405216/132161288-1643e8b6-3140-44e9-a982-933a90a125ec.png)

**Comment by rangerzhou** [comment]
第一次启动的时候才会弹出 wine 更新 界面提示，后续点击图标，没有任何反应

**Comment by rangerzhou** [comment]
```
# ranger @ mintos in /opt/apps/com.qq.weixin.deepin/files [16:46:28] C:130
$ sudo ./run.sh
Run Deepin-WeChat 3.2.1.154deepin13 c:/Program Files/Tencent/WeChat/WeChat.exe
run Deepin-WeChat progress pid 
total 0
lrwxrwxrwx 1 root root 10 9月   6 16:46 c: -> ../drive_c
lrwxrwxrwx 1 root root 10 9月   6 16:46 com1 -> /dev/ttyS0
lrwxrwxrwx 1 root root 10 9月   6 16:46 com10 -> /dev/ttyS9
lrwxrwxrwx 1 root root 11 9月   6 16:46 com11 -> /dev/ttyS10
lrwxrwxrwx 1 root root 11 9月   6 16:46 com12 -> /dev/ttyS11
lrwxrwxrwx 1 root root 11 9月   6 16:46 com13 -> /dev/ttyS12
lrwxrwxrwx 1 root root 11 9月   6 16:46 com14 -> /dev/ttyS13
lrwxrwxrwx 1 root root 11 9月   6 16:46 com15 -> /dev/ttyS14
lrwxrwxrwx 1 root root 11 9月   6 16:46 com16 -> /dev/ttyS15
lrwxrwxrwx 1 root root 11 9月   6 16:46 com17 -> /dev/ttyS16
lrwxrwxrwx 1 root root 11 9月   6 16:46 com18 -> /dev/ttyS17
lrwxrwxrwx 1 root root 11 9月   6 16:46 com19 -> /dev/ttyS18
lrwxrwxrwx 1 root root 10 9月   6 16:46 com2 -> /dev/ttyS1
lrwxrwxrwx 1 root root 11 9月   6 16:46 com20 -> /dev/ttyS19
lrwxrwxrwx 1 root root 11 9月   6 16:46 com21 -> /dev/ttyS20
lrwxrwxrwx 1 root root 11 9月   6 16:46 com22 -> /dev/ttyS21
lrwxrwxrwx 1 root root 11 9月   6 16:46 com23 -> /dev/ttyS22
lrwxrwxrwx 1 root root 11 9月   6 16:46 com24 -> /dev/ttyS23
lrwxrwxrwx 1 root root 11 9月   6 16:46 com25 -> /dev/ttyS24
lrwxrwxrwx 1 root root 11 9月   6 16:46 com26 -> /dev/ttyS25
lrwxrwxrwx 1 root root 11 9月   6 16:46 com27 -> /dev/ttyS26
lrwxrwxrwx 1 root root 11 9月   6 16:46 com28 -> /dev/ttyS27
lrwxrwxrwx 1 root root 11 9月   6 16:46 com29 -> /dev/ttyS28
lrwxrwxrwx 1 root root 10 9月   6 16:46 com3 -> /dev/ttyS2
lrwxrwxrwx 1 root root 11 9月   6 16:46 com30 -> /dev/ttyS29
lrwxrwxrwx 1 root root 11 9月   6 16:46 com31 -> /dev/ttyS30
lrwxrwxrwx 1 root root 11 9月   6 16:46 com32 -> /dev/ttyS31
lrwxrwxrwx 1 root root 10 9月   6 16:46 com4 -> /dev/ttyS3
lrwxrwxrwx 1 root root 10 9月   6 16:46 com5 -> /dev/ttyS4
lrwxrwxrwx 1 root root 10 9月   6 16:46 com6 -> /dev/ttyS5
lrwxrwxrwx 1 root root 10 9月   6 16:46 com7 -> /dev/ttyS6
lrwxrwxrwx 1 root root 10 9月   6 16:46 com8 -> /dev/ttyS7
lrwxrwxrwx 1 root root 10 9月   6 16:46 com9 -> /dev/ttyS8
lrwxrwxrwx 1 root root  8 9月   6 16:46 d:: -> /dev/sr0
lrwxrwxrwx 1 root root  5 9月   6 16:46 y: -> /root
lrwxrwxrwx 1 root root  1 9月   6 16:46 z: -> /
CallApp Deepin-WeChat arg count 1: c:/Program Files/Tencent/WeChat/WeChat.exe
Disable auto update
rm: cannot remove '/root/.deepinwine/Deepin-WeChat/drive_c/users/root/Application Data/Tencent/WeChat/All Users/config/configEx.ini': No such file or directory
2021年 09月 06日 星期一 16:46:49 CST:kill Deepin-WeChat block
2021年 09月 06日 星期一 16:46:49 CST:tag bottle: /root/.deepinwine/Deepin-WeChat
Traceback (most recent call last):
  File "/opt/deepinwine/tools/get_tray_window", line 28, in <module>
    get_tray_window()
  File "/opt/deepinwine/tools/get_tray_window", line 18, in get_tray_window
    traymanager = bus.get_object("com.deepin.dde.TrayManager", "/com/deepin/dde/TrayManager")
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 243, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 280, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 653, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name com.deepin.dde.TrayManager was not provided by any .service files
2021年 09月 06日 星期一 16:46:50 CST:active bottles: 
2021年 09月 06日 星期一 16:46:50 CST:try to kill /root/.deepinwine/Deepin-WeChat
2021年 09月 06日 星期一 16:46:50 CST:kill /root/.deepinwine/Deepin-WeChat by /opt/deepin-wine6-stable/bin/wineserver.real
/root/.deepinwine/Deepin-WeChat/drive_c/Program Files/Tencent/WeChat

# ranger @ mintos in /opt/apps/com.qq.weixin.deepin/files [16:46:50] 
$ wine version: 6.0
[0906/164653:INFO:exception_record.cc(518)] [QB]Process ID: 32 Type: 1
X Error of failed request:  GLXBadFBConfig
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  0 ()
  Serial number of failed request:  313
  Current serial number in output stream:  313

```

**Comment by CeciliaKasumi** [comment]
我也是一样的问题，楼主弄好了吗

**Comment by rangerzhou** [comment]
> 我也是一样的问题，楼主弄好了吗

没有，卸载重装了好几次都不行，就差重装系统了

**Comment by CeciliaKasumi** [comment]
> > 我也是一样的问题，楼主弄好了吗
> 
> 没有，卸载重装了好几次都不行，就差重装系统了

重装系统就好了吗？

**Comment by XBYoung** [comment]
同问啊，头大

**Comment by rangerzhou** [comment]
> > > 我也是一样的问题，楼主弄好了吗
> > 
> > 
> > 没有，卸载重装了好几次都不行，就差重装系统了
> 
> 重装系统就好了吗？

没有尝试，估计不行

**Comment by rangerzhou** [comment]
你们也都是突然就不能用了吗，我还以为是我安装Linux百度输入法导致的

**Comment by rangerzhou** [comment]
尝试过 `sudo run.sh -r` ，还是不行

**Comment by chaojie-fu** [comment]
Ubuntu20.04同样无法使用，钉钉、qq都能用，就微信出问题了

**Comment by yyy624297803** [comment]
我是新装的系统，然后装的deepin-wine中的微信，也是同样的问题，但是我同学用之前的版本的微信是没问题的，也是通过这个deepin-wine安装的，有没有作者来维护一下，或者来一个老版本微信安装的文档？

**Comment by phpluo** [comment]
> Ubuntu20.04同样无法使用，钉钉、qq都能用，就微信出问题了

Ubuntu20.04 我的是正常的

**Comment by evanbean** [comment]
evan@HP-Stream-Notebook:~/Desktop$ echo $XDG_CURRENT_DESKTOP
MATE
evan@HP-Stream-Notebook:~/Desktop$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
evan@HP-Stream-Notebook:~/Desktop$ grep -rn '^\s*deb ' --include '*.list' /etc/apt/
/etc/apt/sources.list.d/google-chrome.list:3:deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
/etc/apt/sources.list.d/deepin-wine.i-m.dev.list:1:deb [trusted=yes] https://deepin-wine.i-m.dev /
我的系统也有一样的问题！哪位大佬能够出手解决一下？

**Comment by yyy624297803** [comment]
我修复了微信的问题，是安装的时候报了软链接的错，或许你们之前没有装Cuda?
```
/sbin/ldconfig.real: /usr/local/cuda/targets/x86_64-linux/lib/libcudnn_adv_train.so.8 is not a symbolic link                                                                                                                                  
                                                                                                                                                                                                                                              
/sbin/ldconfig.real: /usr/local/cuda/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8 is not a symbolic link                                                                                                                                  
                                                                                                                                                                                                                                              
/sbin/ldconfig.real: /usr/local/cuda/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8 is not a symbolic link                                                                                                                                  
                                                                                                                                                                                                                                              
/sbin/ldconfig.real: /usr/local/cuda/targets/x86_64-linux/lib/libcudnn_ops_train.so.8 is not a symbolic link

/sbin/ldconfig.real: /usr/local/cuda/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8 is not a symbolic link

/sbin/ldconfig.real: /usr/local/cuda/targets/x86_64-linux/lib/libcudnn.so.8 is not a symbolic link

/sbin/ldconfig.real: /usr/local/cuda/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8 is not a symbolic link
```
我把`.so.8`结尾的cudann文件改为具体`.so.8.x`的软链接 重新安装就可以使用了，不过我可能之前没装Cudann的原因，我今天装了Cudann，之后重装之后就可以使用微信了。

**Comment by rangerzhou** [comment]
> 我修复了微信的问题，是安装的时候报了软链接的错，或许你们之前没有装Cuda?
> 
> ```
> /sbin/ldconfig.real: /usr/local/cuda/targets/x86_64-linux/lib/libcudnn_adv_train.so.8 is not a symbolic link                                                                                                                                  
>                                                                                                                                                                                                                                               
> /sbin/ldconfig.real: /usr/local/cuda/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8 is not a symbolic link                                                                                                                                  
>                                                                                                                                                                                                                                               
> /sbin/ldconfig.real: /usr/local/cuda/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8 is not a symbolic link                                                                                                                                  
>                                                                                                                                                                                                                                               
> /sbin/ldconfig.real: /usr/local/cuda/targets/x86_64-linux/lib/libcudnn_ops_train.so.8 is not a symbolic link
> 
> /sbin/ldconfig.real: /usr/local/cuda/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8 is not a symbolic link
> 
> /sbin/ldconfig.real: /usr/local/cuda/targets/x86_64-linux/lib/libcudnn.so.8 is not a symbolic link
> 
> /sbin/ldconfig.real: /usr/local/cuda/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8 is not a symbolic link
> ```
> 
> 我把`.so.8`结尾的cudann文件改为具体`.so.8.x`的软链接 重新安装就可以使用了，不过我可能之前没装Cudann的原因，我今天装了Cudann，之后重装之后就可以使用微信了。

看 log 报错不一样吧

**Comment by rangerzhou** [comment]
不知道怎么折腾的，今天能用了……  真的不知道怎么好的。。。

**Comment by yyy624297803** [comment]
> > 我修复了微信的问题，是安装的时候报了软链接的错，或许你们之前没有装Cuda?
> > ```
> > /sbin/ldconfig.real: /usr/local/cuda/targets/x86_64-linux/lib/libcudnn_adv_train.so.8 is not a symbolic link                                                                                                                                  
> >                                                                                                                                                                                                                                               
> > /sbin/ldconfig.real: /usr/local/cuda/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8 is not a symbolic link                                                                                                                                  
> >                                                                                                                                                                                                                                               
> > /sbin/ldconfig.real: /usr/local/cuda/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8 is not a symbolic link                                                                                                                                  
> >                                                                                                                                                                                                                                               
> > /sbin/ldconfig.real: /usr/local/cuda/targets/x86_64-linux/lib/libcudnn_ops_train.so.8 is not a symbolic link
> > 
> > /sbin/ldconfig.real: /usr/local/cuda/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8 is not a symbolic link
> > 
> > /sbin/ldconfig.real: /usr/local/cuda/targets/x86_64-linux/lib/libcudnn.so.8 is not a symbolic link
> > 
> > /sbin/ldconfig.real: /usr/local/cuda/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8 is not a symbolic link
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我把`.so.8`结尾的cudann文件改为具体`.so.8.x`的软链接 重新安装就可以使用了，不过我可能之前没装Cudann的原因，我今天装了Cudann，之后重装之后就可以使用微信了。
> 
> 看 log 报错不一样吧

我没有运行`sudo ./run.sh`, 我这个是重装的时候的log报错，然后把cudnn改成软链接就OK了，不过你现在可以使用就最好了～如果有人是安装的时候报相关cudnn的错可以参考以下～

**Comment by rangerzhou** [comment]
> 

检查一下是不是电脑显卡驱动有问题，我之前好像是集成显卡驱动有问题，装好后就正常了

**Comment by xinyangmaojian** [comment]
> > 
> 
> 检查一下是不是电脑显卡驱动有问题，我之前好像是集成显卡驱动有问题，装好后就正常了

是的   我也出了这个问题   之前并不确定是否为驱动问题，还把deepin-wine环境卸载换成了wine，依然报这个错误，升级了一下mesa的驱动就可以了

**Comment by xinyangmaojian** [comment]
补充一下   升级驱动
https://www.linuxmi.com/ubuntu-20-04-21-04-anzhuang-mesa.html
