### ISSUE TITLE
Ubuntu20.04 安装企业微信后无法打开

### ISSUE THREAD

**Issue by windskr** [zq1997/deepin-wine#291]
# 桌面有图标，但点击没有反应。安装的微信可以正常打开。
## 从runsh打开也不行，有如下报错：
`
indskr@windskr-ThinkPad-P15v-Gen-2i:/opt/apps/com.qq.weixin.work.deepin/files$ ./run.sh 
Don't use public dir
Run Deepin-WXWork 4.0.0.6007deepin10 c:/Program Files/WXWork/WXWork.exe
run Deepin-WXWork progress pid 
总用量 0
lrwxrwxrwx 1 windskr windskr 10 6月  11 17:00 c: -> ../drive_c
lrwxrwxrwx 1 windskr windskr 10 6月  11 16:56 com1 -> /dev/ttyS0
lrwxrwxrwx 1 windskr windskr 10 6月  11 16:56 com10 -> /dev/ttyS9
lrwxrwxrwx 1 windskr windskr 11 6月  11 16:56 com11 -> /dev/ttyS10
lrwxrwxrwx 1 windskr windskr 11 6月  11 16:56 com12 -> /dev/ttyS11
lrwxrwxrwx 1 windskr windskr 11 6月  11 16:56 com13 -> /dev/ttyS12
lrwxrwxrwx 1 windskr windskr 11 6月  11 16:56 com14 -> /dev/ttyS13
lrwxrwxrwx 1 windskr windskr 11 6月  11 16:56 com15 -> /dev/ttyS14
lrwxrwxrwx 1 windskr windskr 11 6月  11 16:56 com16 -> /dev/ttyS15
lrwxrwxrwx 1 windskr windskr 11 6月  11 16:56 com17 -> /dev/ttyS16
lrwxrwxrwx 1 windskr windskr 11 6月  11 16:56 com18 -> /dev/ttyS17
lrwxrwxrwx 1 windskr windskr 11 6月  11 16:56 com19 -> /dev/ttyS18
lrwxrwxrwx 1 windskr windskr 10 6月  11 16:56 com2 -> /dev/ttyS1
lrwxrwxrwx 1 windskr windskr 11 6月  11 16:56 com20 -> /dev/ttyS19
lrwxrwxrwx 1 windskr windskr 11 6月  11 16:56 com21 -> /dev/ttyS20
lrwxrwxrwx 1 windskr windskr 11 6月  11 16:56 com22 -> /dev/ttyS21
lrwxrwxrwx 1 windskr windskr 11 6月  11 16:56 com23 -> /dev/ttyS22
lrwxrwxrwx 1 windskr windskr 11 6月  11 16:56 com24 -> /dev/ttyS23
lrwxrwxrwx 1 windskr windskr 11 6月  11 16:56 com25 -> /dev/ttyS24
lrwxrwxrwx 1 windskr windskr 11 6月  11 16:56 com26 -> /dev/ttyS25
lrwxrwxrwx 1 windskr windskr 11 6月  11 16:56 com27 -> /dev/ttyS26
lrwxrwxrwx 1 windskr windskr 11 6月  11 16:56 com28 -> /dev/ttyS27
lrwxrwxrwx 1 windskr windskr 11 6月  11 16:56 com29 -> /dev/ttyS28
lrwxrwxrwx 1 windskr windskr 10 6月  11 16:56 com3 -> /dev/ttyS2
lrwxrwxrwx 1 windskr windskr 11 6月  11 16:56 com30 -> /dev/ttyS29
lrwxrwxrwx 1 windskr windskr 11 6月  11 16:56 com31 -> /dev/ttyS30
lrwxrwxrwx 1 windskr windskr 11 6月  11 16:56 com32 -> /dev/ttyS31
lrwxrwxrwx 1 windskr windskr 10 6月  11 16:56 com4 -> /dev/ttyS3
lrwxrwxrwx 1 windskr windskr 10 6月  11 16:56 com5 -> /dev/ttyS4
lrwxrwxrwx 1 windskr windskr 10 6月  11 16:56 com6 -> /dev/ttyS5
lrwxrwxrwx 1 windskr windskr 10 6月  11 16:56 com7 -> /dev/ttyS6
lrwxrwxrwx 1 windskr windskr 10 6月  11 16:56 com8 -> /dev/ttyS7
lrwxrwxrwx 1 windskr windskr 10 6月  11 16:56 com9 -> /dev/ttyS8
lrwxrwxrwx 1 windskr windskr 13 6月  11 17:00 y: -> /home/windskr
lrwxrwxrwx 1 windskr windskr  1 6月  11 17:00 z: -> /
CallApp Deepin-WXWork arg count 1: c:/Program Files/WXWork/WXWork.exe
Don't use public dir
2022年 06月 11日 星期六 17:00:15 CST:kill Deepin-WXWork block
2022年 06月 11日 星期六 17:00:15 CST:tag bottle: /home/windskr/.deepinwine/Deepin-WXWork
Traceback (most recent call last):
  File "/opt/deepinwine/tools/get_tray_window", line 28, in <module>
    get_tray_window()
  File "/opt/deepinwine/tools/get_tray_window", line 18, in get_tray_window
    traymanager = bus.get_object("com.deepin.dde.TrayManager", "/com/deepin/dde/TrayManager")
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 243, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 280, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 653, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name com.deepin.dde.TrayManager was not provided by any .service files
2022年 06月 11日 星期六 17:00:15 CST:active bottles: 
2022年 06月 11日 星期六 17:00:15 CST:try to kill /home/windskr/.deepinwine/Deepin-WXWork
/opt/deepinwine/tools/kill.sh: 行 66: /proc/40701/environ: 没有那个文件或目录
cat: /proc/40701/maps: 没有那个文件或目录
cat: /proc/40701/cmdline: 没有那个文件或目录
cat: /proc/40701/maps: 没有那个文件或目录
cat: /proc/934/maps: 权限不够
cat: /proc/934/maps: 权限不够
cat: /proc/1479/maps: 权限不够
cat: /proc/1479/maps: 权限不够
cat: /proc/2111/maps: 权限不够
cat: /proc/2111/maps: 权限不够
cat: /proc/2249/maps: 权限不够
cat: /proc/2249/maps: 权限不够
cat: /proc/40726/maps: 没有那个文件或目录
cat: /proc/40726/cmdline: 没有那个文件或目录
cat: /proc/40726/maps: 没有那个文件或目录
windskr    41754   40454  0 17:00 pts/0    00:00:00 grep -E windskr.*exe.*<defunct>
/home/windskr/.deepinwine/Deepin-WXWork/drive_c/Program Files/WXWork
windskr@windskr-ThinkPad-P15v-Gen-2i:/opt/apps/com.qq.weixin.work.deepin/files$ MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

wine version: 6.0

`

# 已经折腾好久，实在没办法了，下面是环境信息
windskr@windskr-ThinkPad-P15v-Gen-2i:~$ echo $XDG_CURRENT_DESKTOP
ubuntu:GNOME
windskr@windskr-ThinkPad-P15v-Gen-2i:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
windskr@windskr-ThinkPad-P15v-Gen-2i:~$ grep -rn '^\s*deb ' --include '*.list' /etc/apt/
/etc/apt/sources.list.d/deepin-wine.i-m.dev.list:1:deb [trusted=yes] https://deepin-wine.i-m.dev /
/etc/apt/sources.list.d/google-chrome.list:3:deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
/etc/apt/sources.list:4:deb http://mirrors.aliyun.com/ubuntu/ bionic main restricted universe multiverse
/etc/apt/sources.list:6:deb http://mirrors.aliyun.com/ubuntu/ bionic-security main restricted universe multiverse
/etc/apt/sources.list:8:deb http://mirrors.aliyun.com/ubuntu/ bionic-updates main restricted universe multiverse
/etc/apt/sources.list:10:deb http://mirrors.aliyun.com/ubuntu/ bionic-proposed main restricted universe multiverse
/etc/apt/sources.list:12:deb http://mirrors.aliyun.com/ubuntu/ bionic-backports main restricted universe multiverse
/etc/apt/sources.list:14:deb http://ftp.sjtu.edu.cn/ubuntu/ focal main restricted
/etc/apt/sources.list:19:deb http://ftp.sjtu.edu.cn/ubuntu/ focal-updates main restricted
/etc/apt/sources.list:25:deb http://ftp.sjtu.edu.cn/ubuntu/ focal universe
/etc/apt/sources.list:27:deb http://ftp.sjtu.edu.cn/ubuntu/ focal-updates universe
/etc/apt/sources.list:35:deb http://ftp.sjtu.edu.cn/ubuntu/ focal multiverse
/etc/apt/sources.list:37:deb http://ftp.sjtu.edu.cn/ubuntu/ focal-updates multiverse
/etc/apt/sources.list:45:deb http://ftp.sjtu.edu.cn/ubuntu/ focal-backports main restricted universe multiverse
/etc/apt/sources.list:55:deb http://ftp.sjtu.edu.cn/ubuntu/ focal-security main restricted
/etc/apt/sources.list:57:deb http://ftp.sjtu.edu.cn/ubuntu/ focal-security universe
/etc/apt/sources.list:59:deb http://ftp.sjtu.edu.cn/ubuntu/ focal-security multiverse
/etc/apt/sources.list:67:deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
/etc/apt/sources.list:69:deb http://archive.ubuntu.com/ubuntu focal main universe restricted multiverse
/etc/apt/sources.list:71:deb https://typora.io/linux ./
windskr@windskr-ThinkPad-P15v-Gen-2i:~$

**Comment by kamusis** [comment]
please check out #277 and #205 
or my whole article: https://www.dbform.com/2022/06/09/renew-alienware-alpha-r1-with-pop_os/

In summary we need to install some packages.

`$ sudo apt install libjpeg62:i386 fonts-wqy-zenhei xfonts-wqy  `

And modify /opt/apps/com.qq.weixin.work.deepin/files/run.sh to comment 2 lines as below.

```
#export WINEDLLPATH=/opt/$APPRUN_CMD/lib:/opt/$APPRUN_CMD/lib64
#export WINEPREDLL="$ARCHIVE_FILE_DIR/dlls"
```

**Comment by windskr** [comment]
> please check out #277 and #205 or my whole article: https://www.dbform.com/2022/06/09/renew-alienware-alpha-r1-with-pop_os/
> 
> In summary we need to install some packages.
> 
> `$ sudo apt install libjpeg62:i386 fonts-wqy-zenhei xfonts-wqy `
> 
> And modify /opt/apps/com.qq.weixin.work.deepin/files/run.sh to comment 2 lines as below.
> 
> ```
> #export WINEDLLPATH=/opt/$APPRUN_CMD/lib:/opt/$APPRUN_CMD/lib64
> #export WINEPREDLL="$ARCHIVE_FILE_DIR/dlls"
> ```

thanks, got it~

**Comment by alicfeng** [comment]
> please check out #277 and #205 or my whole article: https://www.dbform.com/2022/06/09/renew-alienware-alpha-r1-with-pop_os/
> 
> In summary we need to install some packages.
> 
> `$ sudo apt install libjpeg62:i386 fonts-wqy-zenhei xfonts-wqy `
> 
> And modify /opt/apps/com.qq.weixin.work.deepin/files/run.sh to comment 2 lines as below.
> 
> ```
> #export WINEDLLPATH=/opt/$APPRUN_CMD/lib:/opt/$APPRUN_CMD/lib64
> #export WINEPREDLL="$ARCHIVE_FILE_DIR/dlls"
> ```

管用、太棒了！治疗企业 微信打开后提示正在配置中...即可闪退 的问题。
